server:
  port: 8082

spring:
  application:
    name: risk-scoring-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:risk_scoring}
    username: ${DB_USER:risksignal}
    password: ${DB_PASSWORD:risksignal}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: risk-scoring-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sahilkalgutkar.risksignal.common.events
        spring.json.value.default.type: com.sahilkalgutkar.risksignal.common.events.TransactionSubmitted
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true

risk:
  amount-threshold: 1000.00
  amount-threshold-score: 40
  country-mismatch-score: 35
  high-risk-countries: KP,IR,SY
  high-risk-country-score: 30
  medium-threshold: 40
  high-threshold: 70

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
